# El algoritmo de factorización Factor Base

In [3]:
from sympy import *

In [4]:
from itertools import *

In [5]:
from TANMLP import *

## Elección de la base. Voy a tener suerte

La primera elección de la base es poco profesional, por ejemplo elegimos la base con el -1 y los primeros 30 primos.

** Ejercicio 0.-** Define la base
$$B=[-1,2,3,...,113],$$ 
que tiene al $-1$ y los primeros 30 primos

In [6]:
def baseprim(b):
    #Hacemos una lista con el -1 y los primeros 'b' primos
    base=[-1]
    for i in range(1,b+1):
        base.append(prime(i))
    return base


Lista de funciones auxiliares que vamos a definir:
   - <span style="color:red">abmod(x,n)</span>,
   - <span style="color:red">mayorpot(b,p)</span>,
   - <span style="color:red">bnumer(b,base,n)</span>,
   - <span style="color:red">vec_alfa(b,base,n)</span>,
   - <span style="color:red">parp(lista)</span>,
   - <span style="color:red">ssuma(lista1,lista2)</span>,
   - <span style="color:red">aux(k,r)</span>,
   - <span style="color:red">suma(lista,k)</span>,

Paso a comentar cada función:

  - La función <span style="color:red">abmod(x,n)</span> tiene como salida $x\%n$ si este es menor o igual que $\frac{n}{2}$ y $x\%n -n$ en caso contrario.  
  
  - La función <span style="color:red">mayorpot(x,p)</span>
     - Si $p=-1$ tiene como salida $1$ si $x<0$ y $0$ en caso contrario.
     - Para cualquier otro $p$ (normalmente primo) tiene como salida el exponente de la mayor potencia de $p$ que divide a $x$. Para definir esta función no puedes factorizar x.
     
  - La función <span style="color:red">bnumer(b,base,n)</span> tiene como salida true si $b$ es un base-número relativo a $n$ y false en caso contrario.
  
  - La función <span style="color:red">vec_alfa(b,base,n)</span> comprueba que $b$ es un base-número y en este caso tiene como salida el vector alfa asociado a $b$. 
Este será una lista de longitud <span style="color:green">len(base)</span> cuyas coordenadas son los exponentes de los elementos de "base" en la descomposición en primos de abmod($b^2,n$) (ver teoría).

  - La función <span style="color:red">parp(lista)</span> vale true si todos los elementos en la lista son pares y false en otro caso.
  
  - La función <span style="color:red">ssuma(lista1,lista2)</span> comprueba que las listas tienen la misma longitud y en ese caso tiene como salida una nueva lista con la misma longitud de las dos listas y que en lugar $i$ tiene a lista1[i]+lista2[i].

Nuestro siguiente objetivo es calcular todas las <span style="color:red">ssumas</span> de k elementos de una lista de listas, de la misma longitud, con $k$ menor o igual que la longitud de cualquier lista de la lista.

   - Para ello vamos a definir una función auxiliar <span style="color:red">aux(k,r)</span> cuya salida sea una lista con todas las listas posibles de la forma $[l_0,l_2,\ldots,l_{k-1}]$ con
$0\leq l_0 < l_2 <\ldots< l_{k-1} \leq r.$
   
   - La función  <span style="color:red">suma(lista,k)</span>: La variable "lista" tiene que ser una lista de listas, todas ellas de la misma longitud, primero comprueba que $k\leq $<span style="color:green">len(lista)</span> y luego da una lista con todas las 
<span style="color:red">ssumas</span> posibles de $k$ elementos de la "lista"
   

In [7]:
def abmod(x,n):
    #Definimos x1 como el resto de x dividido por n
    x1=x%n
    #Comprobamos si x1 es menor o igual que (n/2)
    if x1<=(n/2):
        #Si cumple la condición devolvemos x1
        return x1
    else:
        #Si no la cumple devolvemos x1-n
        return x1-n
        

In [8]:
def mayorpot(p,m):
    #Comprobamos si p es -1
    if p==-1:
        if m<0:
            return 1
        else:
            return 0
    #Quitamos casos triviales
    if p==0:
        return "Es una trivialidad preguntarse cual es la mayor potencia de 0 que divide a m"
    if p==1:
        return 1
    #Comprobamos si p divide a m
    if m%p!=0:
        return 0
    #Si p divide a m usamos de variable auxiliar a, con la cual iremos haciendo las potencias de p
    #Y comprobar hasta que potencia se divide a m, usamos i como variable auxiliar para ver el exponente de la potencia
    else:
        i=1
        a=p
        while m%(a*p)==0:
            i=i+1
            a=a*p
        #Devuelve el exponente de la mayor potencia que divide a m
        return i

In [11]:
def bnumer(b,base,n):
    #Hacemos la b^2 mod n con nuestra función abmod
    #Llamamos b1 a ese número
    b1=abmod(b**2,n)
    #Hacemos la mayor potencia de los primos que divida a este número
    #Y los vamos multiplicando en la variable prod
    prod=1
    for i in range(0,len(base)):
        #Llamamos x a la mayor potencia
        x=base[i]**mayorpot(base[i],b1)
        prod=prod*x
    #Comprobamos si el producto es el número b
    if prod==b1:
        return true
    else:
        return false
    

In [12]:
def vec_alfa(b,base,n):
    #Comprueba si b es un b-numero
    if bnumer(b,base,n)==false:
        return
    else:
        #Definimos el vector alfa como los exponentes asociados al bnumero en la base
        vecalfa=[]
        #Definimos b1 como b^2 mod n con nuestra función abmod
        b1=b1=abmod(b**2,n)
        for i in range(0,len(base)):
            vecalfa=vecalfa+[mayorpot(base[i],b1)]
        return vecalfa

In [13]:
def parp(lista):
    #Devolvemos true si todos los elementos de la lista son pares, en otro caso false.
    for i in range(0,len(lista)):
        if lista[i]%2!=0:
            return false
    return true

In [14]:
def ssuma(lista1,lista2):
    #Sumamos elemento a elemento dos listas
    if len(lista1)!=len(lista2):
        print 'No tienen la misma dimensión las dos listas'
        return
    #Definimos la lista en la que vamos a sumar estas dos
    listsuma=[]
    for i in range(0,len(lista1)):
        listsuma=listsuma+[lista1[i]+lista2[i]]
    return listsuma
    

In [15]:
def aux(k,r):
    #Lista con el número total de elementos r
    lista=range(0,r)
    #Lista de listas con las posibles combinaciones de elementos de lista tomados de k en k
    aux=list(combinations(lista, k))
    return aux
    

In [16]:
def ssuman(lista):
    #Sumar n listas, que son los elementos de una lista.
    suma=lista[0]
    for i in range(1,len(lista)):
        suma=ssuma(suma,lista[i])
    return suma
        

In [17]:
def suma(lista,k):
    r=len(lista)
    #lista es una lista de listas
    #comprobamos que la longitud de la lista sea mayor que k
    if len(lista)<=k:
        return
    #definimos la salida de la función que es una lista con todas las ssumas de k en k
    aux1=aux(k,r)
    m=factorial(r)/(factorial(k)*factorial(r-k))
    lista1=[[]]

    for i in range(0,m):
        if i>0:
            lista1.append([])
        for j in aux1[i]:
            if j==aux1[i][0]:
                lista1[i]=lista1[i]+lista[j]
            elif j==aux1[i][1]:
                lista1[i]=[lista1[i]]+[lista[j]]
            else:
                lista1[i]=lista1[i]+[lista[j]]
    lista2=[]
    for i in range(0,m):
        lista2.append(ssuman(lista1[i]))
    return lista2
            
    
    
    
    
        
    

## Elección de la lista de $B$ números. Voy a seguir teniendo suerte

Vamos a elegir una lista de $B$-números con la esperanza de que sean suficientes para resolver la ecuación #eq. El proceso será el siguiente:

 - Fijamos $k_{max}$ y también $i_{max}$. 
 - Construimos la lista 
 $$L_1=[n_k=\mbox{ floor(sqrt($k*n$)), para } k=1,2,3,4,\ldots,k_{max}].$$ 
 - Construimos la lista $$L_2=[ b_{ki}=n_k + i, \mbox{ para } n_k \in L_1 \mbox{ e } i=0,2,3,\ldots,i_{max}-1]$$
 
 - Seleccionamos de $L_2$ aquellos $b_{ki}$ que son B-números y formamos la lista BN con ellos.
 
Define una función <span style="color:red">bi(n,k,i,base)</span> que realice el proceso de selección anterior.

In [18]:
def bi(n,k,i,base):
    #Definimos la lista L1
    L1=[]
    for l in range(1,k+1):
        L1=L1+[floor(sqrt(l*n))]
    #Definimos la lista L2
    L2=[]
    for l in range(0,len(L1)):
        for j in range(0,i):
            L2=L2+[L1[l]+j]
    #Seleccionamos aquellos números de L2 que sean B-números
    BN=[]
    for l in range(0,len(L2)):
        if bnumer(L2[l],base,n)==true:
            BN=BN+[L2[l]]
    return BN

## Algoritmo de resolución de la ecuación $x^2=y^2 \mod n$

- Imput n
- output (t,s) con $t^2=s^2\mod n$

    - **paso 1.-** Elegimos una base $B$ y esperamos tener suerte.
    - **paso 2.-** Elegimos índices $k_{max}$ e $i_{max}$ y construimos la lista de $B$-números <span style="color:green">BN</span>= <span style="color:red">bi(n,$k_{max}$,$i_{max}$,base)</span> y volvemos a esperar tener suerte.
    - **paso 3.-** Construimos la lista <span style="color:green">alfavec</span> de alfa vectores correspondientes a los $B$-números en $BN$.
    - **paso 4.-** Inicializamos el índice $j=1$, construimos la lista <span style="color:green">sumaj</span>=<span style="color:red">suma(alfavec,j)</span> y nos quedamos con las sublista <span style="color:green">sumajpar</span>  de sumaj cuyos elementos satisfagan la condición <span style="color:red">parp</span>. Si <span style="color:green">sumajpar</span> es vacía tomamos $j=j+1$ y repetimos el proceso anterior.
    - **paso 5.-** Inicializamos $\alpha$ como el primer elemento de <span style="color:green">sumajpar</span>, tomamos $in_\alpha$ como el lugar que ocupa $\alpha$ en <span style="color:green">sumaj</span>. Esto nos permite calcular la lista de eles para $\alpha$,
<center> <span style="color:green">eles$\alpha$</span> = <span style="color:red">aux(len(B),j)[in_$\alpha$]</span> = $[l_0,l_2,\ldots,l_{j-1}]$</center>
además tenemos que $$\alpha=\alpha_{l_0}+\ldots +\alpha_{l_{j-1}}.$$
Si ponemos $\alpha_{l_i}=(e_{l_i}^0,\ldots,e_{l_i}^h)$ y $\alpha=(e_0,\ldots,e_h)$ entonces:
$$ e_r=\sum_{i=0}^{j-1} e_{l_i}^r$$
    - **paso 6.-** Calculamos:
    $$ t=\prod_{i=0}^{j-1} b_{l_i} \quad\mbox{y}\quad s=\prod_{r=0}^h p_r^{\frac{e_r}{2}}$$
    - **paso 7.-** Si $(t,s)$ es una solución no trivial return $(t,s)$. En caso contrario volvemos al paso 5 tomando $\alpha=$ siguiente de $\alpha$.
    - **Fin.-** Si todas las soluciones que hemos obtenido son triviales no hemos tenido suerte y cambiamos primero los índices $k_{max}$ e $i_{max}$ y si aún así no tenemos suerte cambiamos la base $B$.

** Ejercicio 1.-** Elije un entero $n$ positivo que empiece por los dígitos de tu DNI, asegúrate de que el $n$ que has elegido no es primo, y realiza el algoritmo anterior paso a paso.

A partir de la solución que has obtenido, da una factorización de $n$.

***Comprueba el resultado.***

### Paso 1. Elección de una base B

Vamos a factorizar mi DNI que es 75908039, usando una base formada por -1 y los 20 primeros primos

In [19]:
#Elegimos como n el número que queremos factorizar, y una base B con los primeros h primos
n=75908039
h=20
B=baseprim(h)

### Paso 2.  Elegimos k e i, y hacemos una lista con los B-números

In [20]:
#Construimos la lista de los B-números, usando los valores de kmax=60 e imax=60
k=60
i=60
BN=bi(n,k,i,B)

### Paso 3. Construimos una lista con los alfa vectores

In [21]:
#Construimos la lista de los alfa vectores asociados a estos B-números
alfavec=[]
for i in range(0,len(BN)):
    alfavec.append(vec_alfa(BN[i],B,n))

### Paso 4. Buscamos la suma de alfavectores que nos dé una lista par

In [22]:
#Elegimos como j el número de alfa vectores que queremos sumar lo empezamos en 1 y lo podemos ir
#subiendo hasta que consigamos una solución no trivial
#j tiene que ser 1 o mayor
#Para cada j guardamos todos las posibles sumas pares en una lista para comprobarlas luego 1 a 1
sumajpar=[]
in_a=[]
j=1
if j>=len(alfavec):
    print'No se pueden sumar tantos elementos, prueba con otros k, i o base'
else:
    for i in range(0,len(alfavec)):
        if parp(alfavec[i])==true:
            sumajpar.append(alfavec[i])
            in_a.append(i)
    if sumajpar==[]:
        while sumajpar==[]:
            j=j+1
            if j>=len(alfavec):
                print'No se pueden sumar tantos elementos, prueba con otros k, i o base'
                break
            sumaj=suma(alfavec,j)
            for i in range(0,len(sumaj)):
                if parp(sumaj[i])==true:
                    sumajpar.append(sumaj[i])
                    in_a.append(i)

### Paso 5. Nos quedamos con la posición de los alfavectores que se han sumado

In [23]:
#Distinguimos los casos en los que se hayan sumado varios alfavectores o sea solo 1
#Guardamos en eles_a todas las posibles combinaciones de suma de alfavectores
#Mientras que en in_a tenemos las posiciones para las cuales la suma da par
if j==1:
    eles_a=in_a
    print eles_a
else:
    eles_a = aux(j,len(BN))

### Paso 6. Calculamos t y s, y si la solución es no trivial  damos la factorización de n

In [24]:
#calculamos t y s para todas las posibilidades de sumas de alfavectores
#usamos l como contador para movernos entre las posibles combinaciones de sumas
#Si t y s es no trivial da una factorización de n
#Si t y s es una solución trivial imprime que no hemos tenido suerte
for l in range(1,len(in_a)):
    t=1
    if j==1:
        t=(t*BN[eles_a[l]])%n
    
    else:
        for i in range(0,len(eles_a[in_a[l]])):
            t=(t*BN[eles_a[in_a[l]][i]])%n
    p=[]
    e=[]
    for i in range (0,len(sumajpar[l])):
        if sumajpar[l][i]!=0:
            p.append(B[i])
            e.append(sumajpar[l][i]/2)
    s=1
    for i in range(0,len(p)):
        s=(s*pow(p[i],e[i],n))%n
    #Comprobamos que sea una solución no trivial
    if gcd(s+t,n)!=1 and gcd(s-t,n)!=1:
        print n,' = ',n/gcd(s+t,n),'*',gcd(s+t,n)
        break
    if l ==len(in_a)-1:
        print 'No hemos tenido suerte'

75908039  =  546101 * 139


Y conseguimos finalmente factorizar mi DNI=75908039 como el producto de dos primos, 546101 y 139

In [25]:
#Comprobamos que es factorización
print 546101*139==75908039

True


** Ejercicio (Avanzado) 2.-** Define una función 
<center><span style="color:red">soleq(n,h,k,i)</span></center>
que haga lo siguiente:
- Tome como Base Factor a la lista formada por $-1$ seguido de los $h$-primeros primos.
- Tome $k$ e $i$ como los índices $k_{max}$ e $i_{max}$ en el algoritmo anterior
- Tenga como salida:
   - print todas las soluciones son triviales, o bien
   - $(t,s)$,  una solución no trivial de la ecuación $x^2\equiv y^2 \mod n$.

Comprueba que tu función "funciona" utilizando el $n$ del ejercicio anterior y viendo que obtienes los mismos resultados.

Aplica la función <span style="color:red">soleq</span> a varios ejemplos y comprueba los resultados.

** Ejercicio (Avanzado) 3.-** Define una función 
<center><span style="color:red">fac(n,h)</span></center>
para factrorizar $n$ que utilice la función soleq. El parámetro $h$ indica el número de primos que van a formar parte de la base factor. He omitido los índices $k$ e $i$ pero puedes añadirlos si los necesitas.

### Ejercicio 2: Una función para resolver la ecuación.

In [26]:
#También devolvemos True o False para saber si hemos podido resolver la ecuación
def soleq(n,h,k,i):
    #Definimos n1 y bp como los valores de n y h
    n1=n
    bp=h
    #Definimos la base con los primeros primos
    B=baseprim(bp)
    #NOs quedamos con los B-números
    BN=bi(n1,k,i,B)
    #Construimos la lista de los alfa vectores asociados a estos B-números
    alfavec=[]
    for i in range(0,len(BN)):
        alfavec.append(vec_alfa(BN[i],B,n1))
    #Elegimos como j el número de alfa vectores que queremos sumar lo empezamos en 1 y lo podemos ir
    #subiendo hasta que consigamos una solución no trivial
    #j tiene que ser 1 o mayor
    #Cuando j es 1 vamos a mirar si hay alfavectores pares y luego comprobaremos uno a uno si dan soluciones
    #Cuando j es mayor que 1 iremos comprobando 1 a 1 si dan solución.
    #Usamos i_0 como contador para saber por qué valor de j vamos comprobando
    #Usamos i_1 como contador para saber dentro de cada valor de j, por qué combinación de alfavectores pares vamos
    i_0=1 
    i_1=0
    for j in range(i_0,len(alfavec)):
        sumajpar=[]
        in_a=[]
        if j==1:
            for i in range(0,len(alfavec)):
                if parp(alfavec[i])==true:
                    #Si encontramos un alfavector par, lo guardamos éste y su posición
                    sumajpar.append(alfavec[i])
                    in_a.append(i)
            #Comprobamos con cada alfavector par
            for l in range(0,len(in_a)):
                eles_a=in_a
                
                #Calculamos t
                t=1
                t=(t*BN[eles_a[l]])%n
                p=[]
                e=[]
                for i in range (0,len(sumajpar)):
                    if sumajpar[l][i]!=0:
                        p.append(B[i])
                        e.append(sumajpar[l][i]/2)
                #Calculamos s
                s=1
                for i in range(0,len(p)):
                    s=(s*pow(p[i],e[i],n))%n
        #Comprobamos que sea una solución no trivial
                if gcd(s+t,n)!=1:
                    return[true,(t,s)]
        #Entramos en este if si no hay ningun alfavector par y tenemos que probar con sumas (j mayor que 1)
        if sumajpar==[]:
            in_a=0
            while sumajpar==[]:
                i_1=0
                j=j+1
                #Ponemos una condición de parada que es que j llegue a 15, 
                #o si el j es mayor que la longitud de alfavec, no podemos hacer las sumas
                if j>=len(alfavec) or j==15:
                    return [false,"No hemos resuelto la ecuación"]
                #Lista con todas las sumas de j en j de alfavectores
                sumaj=suma(alfavec,j)
                for i in range(i_1,len(sumaj)):
                    #Comprobamos una a una si la suma de alfavectores es par
                     if parp(sumaj[i])==true:
                        #Si es par procedemos a comprobar si da solución
                        sumajpar=sumaj[i]
                        in_a=i
                        i_0=j
                        i_1=i   
    #Vemos cual es la combinación que se ha sumado para obtener el par
                        eles_a =aux(j,len(BN))
                        #Calculamos t 
                        t=1
                        for i in range(0,len(eles_a[in_a])):
                            t=(t*BN[eles_a[in_a][i]])%n
                        p=[]
                        e=[]
                        for i in range (0,len(sumajpar)):
                            if sumajpar[i]!=0:
                                p.append(B[i])
                                e.append(sumajpar[i]/2)
                        #Calculamos s
                        s=1
                        for i in range(0,len(p)):
                            s=(s*pow(int(p[i]),int(e[i]),int(n)))%n
        #Comprobamos que sea una solución no trivial
                        if gcd(s+t,n)!=1 and gcd(s-t,n)!=1:
                            return[true,(t,s)]
    return [false]

In [27]:
#Probemos a resolver la ecuación con la función definida
sol=soleq(75908039,30,30,30)
print sol
print (sol[1][0]**2-sol[1][1]**2)%75908039
#Vemos que ha conseguido resolver la ecuación que se planteaba antes.
#Vemos que no sea trivial
print gcd(sol[1][0]-sol[1][1],75908039)!=1 and gcd(sol[1][0]+sol[1][1],75908039)!=1
#Comprobamos que no es trivial

[True, (73161896, 25136284)]
0
True


In [28]:
#Probemos ahora con otro ejemplo
sol2=soleq(492329,30,30,30)
print sol2
print (sol2[1][0]**2-sol2[1][1]**2)%492329
#Volvemos a resolver la ecuación, comprobamos que sea no trivial
print gcd(sol2[1][0]-sol2[1][1],492329)!=1 and gcd(sol2[1][0]+sol2[1][1],492329)!=1
#Comprobamos que no es trivial

[True, (2105, 8)]
0
True


### Ejercicio 3: Una función para factorizar.

In [29]:
def fac(n,h):
    n1=n
    h1=h
    i=5
    k=5
    factorizacion=true
    sol=soleq(n1,h1,k,i)
    if sol[0]==true:
        s=sol[1][0]
        t=sol[1][1]
    else:
        while sol[0]==false:
            k=k+5
            i=i+5
            sol=soleq(n1,h1,k,i)
            if sol[0]==true:
                s=sol[1][0]
                t=sol[1][1]
            if i==100:
                factorizacion=false
                break
    if factorizacion==false:
        print 'Peligro de bucle infinito, elige otro h'
    else: 
        return (gcd(s+t,n),n/gcd(s+t,n))

In [30]:
#Probemos a volver a factorizar mi DNI con esta función
print fac(75908039,20)

(546101, 139)


In [31]:
#Probemos ahora a factorizar otro número como el producto de dos primos en este caso
f=fac(78776227,20)
print f
#Comprobamos que factoriza
print f[0]*f[1]==78776227

(93893, 839)
True


## Elección de la base. Fracciones continuas

La función <span style="color:green">continued_fraction_periodic(a,b,d)</span> calcula la fracción continua asociada a $\frac{a+\sqrt d}{b}$

In [32]:
F=continued_fraction_periodic(0,1,9073) # (0+sqrt(9073))/1
print F

[95, [3, 1, 26, 2, 6, 1, 1, 3, 2, 1, 5, 3, 1, 7, 5, 1, 1, 1, 4, 4, 4, 1, 1, 1, 5, 7, 1, 3, 5, 1, 2, 3, 1, 1, 6, 2, 26, 1, 3, 190]]


la función <span style="color:green">continued_fraction_convergents(lista)</span> calcula los convergentes

In [33]:
L1=[F[0]]+F[1][:5]
print L1

[95, 3, 1, 26, 2, 6]


In [34]:
L2=continued_fraction_convergents(L1)

In [35]:
L3=list(L2)
print L3

[95, 286/3, 381/4, 10192/107, 20765/218, 134782/1415]


In [36]:
L3[1]

286/3

In [37]:
fraction(L3[1])[0]

286

### Algoritmo de elección de la Base factor y de los B-números

- **Paso 1.-** Calculamos la fracción continua asociada a $\sqrt n$
<center> F = <span style="color:green">continued_fraction_periodic(0,1,n).</span></center>
- **Paso 2.-** Formamos la lista
<center> $L_1 =$ <span style="color:green">F[0]+F[1].</span></center>
- **Paso 3.-** Elegimos $s\leq len(L_1)$, calculamos los convergentes 
<center> $L_2 = $<span style="color:green">continued_fraction_convergents($L_1$[:s]).</span></center>
- **Paso 4.-** Formamos la lista Pbs cuyos elementos son los numeradores de los elementos en $L_2$.
- **Paso 5.-** Para cada $b\in Pbs$ factorizamos <span style="color:green">abmod $(b^2,n)$.</span>
- **Paso 6.-** La base factor $B$ estará formada por $-1$ junto con los primos que:
   - aparecen en la factorización de <span style="color:green">abmod $(b^2,n)$</span> para al menos dos b's en Pbs, o bien
   - aparece con un exponente par en la factorización de <span style="color:green">abmod $(b^2,n)$</span> para exactamente un b.
-  **Paso 7.-** La lista de B-números estará formada por aquellos b's en Pbs que sean B-números para la base obtenida en el paso anterior.

** Ejercicio 4.-** Elije un entero $n$ positivo que empiece por los dígitos de tu DNI, asegúrate de que el $n$ que has elegido no es primo y que es distinto del que elegiste en el ejercicio 1, y realiza el algoritmo anterior paso a paso obteniendo una base $B$ y una lista de $B$-números $BN$.

** Ejercicio 5.-** Completa el ejercicio 3 resolviendo la ecuación $x^2\equiv y^2\mod n$ utilizando como base factor y lista de B-números los obtenidos en el ejercicio 3. 

** Ejercicio 5.-** Completa el ejercicio 4 factorizando el $n$ que has elegido.

** Ejercicio (Avanzado) 6.-** Automatiza los procesos de elección de base factor y resolución de la ecuación, para ello define una función  <span style="color:red">soleqfc(n,s)</span>.

** Ejercicio (Avanzado) 7.-** Define una función <span style="color:red">facfc(n)</span> que factorice $n$ utilizando la función soleqfc.


### Paso 1: Calculamos la fracción continua asociada a $\sqrt n$

In [38]:
#Para este algoritmo vamos a factorizar mi DNI con un 1 al final, 759080391
n=759080391
F = continued_fraction_periodic(0,1,n)

### Paso 2:  Formamos la lista $L_{1}=F[0]+F[1]$

In [39]:
L1= [F[0]]+F[1]

### Paso 3: Elegimos $s\leq len(L_1)$, calculamos los convergentes 

In [40]:
s=30
if s<=len(L1):
    L2=list(continued_fraction_convergents(L1[:s]))
print L2


[27551, 55103/2, 137757/5, 330617/12, 468374/17, 798991/29, 4463329/162, 9725649/353, 14188978/515, 38103605/1383, 128499793/4664, 295103191/10711, 423602984/15375, 718706175/26086, 5454546209/197977, 6173252384/224063, 11627798593/422040, 99195641128/3600383, 110823439721/4022423, 320842520570/11645229, 431665960291/15667652, 1184174441152/42980533, 7536712607203/273550850, 23794312262761/863633083, 31331024869964/1137183933, 86456362002689/3138000949, 290700110878031/10551186780, 2121357138148906/76996308409, 19382914354218185/703517962461, 176567586326112571/6408657970558]


### Paso 4: Formamos la lista Pbs cuyos elementos son los numeradores de los elementos en $L_2$.

In [41]:
Pbs=[]
for i in range(0,len(L2)):
    Pbs.append(fraction(L2[i])[0])
print Pbs 

[27551, 55103, 137757, 330617, 468374, 798991, 4463329, 9725649, 14188978, 38103605, 128499793, 295103191, 423602984, 718706175, 5454546209, 6173252384, 11627798593, 99195641128, 110823439721, 320842520570, 431665960291, 1184174441152, 7536712607203, 23794312262761, 31331024869964, 86456362002689, 290700110878031, 2121357138148906, 19382914354218185, 176567586326112571]


### Paso 5 y 6:  Para cada $b\in Pbs$ factorizamos <span style="color:green">abmod $(b^2,n)$</span>. La base factor $B$ estará formada por $-1$ junto con los primos que:  aparecen en la factorización de <span style="color:green">abmod $(b^2,n)$</span> para al menos dos b's en Pbs, o bien

In [42]:
#Esta función asignará la base según los Pbs
def elecbase(Pbs):
#Lista de los Pbs
    Pbs1=Pbs
#Ceamos una lista donde guardar la factorización de todos los b números
    factorb=[]
#Inicializamos nuestra lista B
    B=[-1]
#Lista que usaremos de apoyo para construir la B, guardaremos en ella los números que no se repitan
#en las factorizaciones, junto al número de los Pbs del cual es factor.
    Baux=[]
#Guardamos las factorizaciones de los números en factorb, junto a la posición del número
#al cual corresponde la factorización en Pbs
    for i in range(0,len(Pbs1)):
        factorb.append([list(factorint(Pbs1[i])),i])
    
#Bucles anidados en los cuales compararemos los factores de los números de Pbs para guardar directamente
#en B los que se repitan dos o más veces y los que salga sólo una vez los guardaremos en Baux
#Para comprobar a continuación si tienen exponente par en la factorización del número del cual es factor
#usamos a como variable booleana para comprobar que no metemos dos veces el mismo valor en B
#b también será una variable booleana y esta llevará os indicará cuando un número sólo sale una vez

    for i in range(0,len(factorb)):
        for j in range(0,len(factorb[i][0])):
            b=false
            for k in range(i+1,len(factorb)):
                for l in range(0,len(factorb[k][0])):
                    a=false
                    if factorb[i][0][j]==factorb[k][0][l]:
                        b=true
                        for m in range(0,len(B)):
                            if(factorb[i][0][j]==B[m]):
                                a=true
                        if a==false:
                             B.append(factorb[i][0][j])
            
            for m in range(0,len(B)):
                if(factorb[i][0][j]==B[m]):
                    b=true
            if b==false:
                Baux.append([factorb[i][0][j],i])

#Comprobamos si tienen exponente par los almacenados en Baux para añadirlos a B             
    for i in range(0,len(Baux)):
        if mayorpot(Baux[i][0],Pbs1[Baux[i][1]])%2==0:
            B.append(Baux[i][0])
    
    return B
    

In [43]:
elecbase(Pbs)

[-1, 3, 47, 7, 2, 13, 5, 19, 11]

In [44]:
#Función para ordenar una lista
def orden(list):
    for i in range(1,len(list)):
        for j in range(0,len(list)-1):
            if(list[j] > list[j+1]):
                k = list[j+1]
                list[j+1] = list[j]
                list[j] = k;
    return list

In [45]:
#Asignamos en B nuestra base, y la ordenamos
B=elecbase(Pbs)
B=orden(B)

### Paso 8: La lista de B-números estará formada por aquellos b's en Pbs que sean B-números para la base obtenida en el paso anterior.

In [46]:
print B
k=60
i=10
#Construimos la lista de los B-números
BN=bi(n,k,i,B)
print BN

[-1, 2, 3, 5, 7, 11, 13, 19, 47]
[47721, 95442, 143163, 190884]


### Paso 9: Resolvemos el problemas con los Base y los B-números elegidos de esta forma.

In [47]:
#Construimos la lista de los alfa vectores asociados a estos B-números
alfavec=[]
for i in range(0,len(BN)):
    alfavec.append(vec_alfa(BN[i],B,n))
print alfavec

[[0, 2, 2, 0, 1, 1, 0, 1, 0], [0, 4, 2, 0, 1, 1, 0, 1, 0], [0, 2, 4, 0, 1, 1, 0, 1, 0], [0, 6, 2, 0, 1, 1, 0, 1, 0]]


In [48]:
#Elegimos como j el número de alfa vectores que queremos sumar lo empezamos en 1 y lo podemos ir
#subiendo hasta que consigamos una solución no trivial
#j tiene que ser 1 o mayor
#Para cada j guardamos todos las posibles sumas pares en una lista para comprobarlas luego 1 a 1
sumajpar=[]
in_a=[]
j=1
if j>=len(alfavec):
    print'No se pueden sumar tantos elementos'
else:
    for i in range(0,len(alfavec)):
        if parp(alfavec[i])==true:
            sumajpar.append(alfavec[i])
            in_a.append(i)
    if sumajpar==[]:
        while sumajpar==[]:
            j=j+1
            if j>=len(alfavec):
                print'No se pueden sumar tantos elementos'
                break
            sumaj=suma(alfavec,j)
            for i in range(0,len(sumaj)):
                if parp(sumaj[i])==true:
                    sumajpar.append(sumaj[i])
                    in_a.append(i)
print sumajpar

[[0, 6, 4, 0, 2, 2, 0, 2, 0], [0, 4, 6, 0, 2, 2, 0, 2, 0], [0, 8, 4, 0, 2, 2, 0, 2, 0], [0, 6, 6, 0, 2, 2, 0, 2, 0], [0, 10, 4, 0, 2, 2, 0, 2, 0], [0, 8, 6, 0, 2, 2, 0, 2, 0]]


In [49]:
#Distinguimos los casos en los que se hayan sumado varios alfavectores o sea solo 1
if j==1:
    eles_a=in_a
    print eles_a
else:
    eles_a = aux(j,len(BN))
    print in_a,eles_a

[0, 1, 2, 3, 4, 5] [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]


In [50]:
#calculamos t y s para todas las posibilidades de sumas de alfavectores
#usamos l como contador para movernos entre las posibles combinaciones de sumas
#Si t y s es no trivial da una factorización de n
#Si t y s es una solución trivial imprime que no hemos tenido suerte
for l in range(1,len(in_a)):
    t=1
    if j==1:
        t=(t*BN[eles_a[l]])%n
    
    else:
        for i in range(0,len(eles_a[in_a[l]])):
            t=(t*BN[eles_a[in_a[l]][i]])%n
    p=[]
    e=[]
    for i in range (0,len(sumajpar[l])):
        if sumajpar[l][i]!=0:
            p.append(B[i])
            e.append(sumajpar[l][i]/2)
    s=1
    for i in range(0,len(p)):
        s=(s*pow(p[i],e[i],n))%n
    #Comprobamos que sea una solución no trivial
    if gcd(s+t,n)!=1:
        print n,' = ',n/gcd(s+t,n),'*',gcd(s+t,n)
        break
    if l ==len(in_a)-1:
        print 'No hemos conseguido factorizar el número'

759080391  =  253026797 * 3


In [51]:
#Comprobamos efectivamente que es una factorización del número
print 759080391==253026797*3

True


### Ejercicio 6: Función soleqfc.

In [52]:
def soleqfc(n,s):
    #Definimos n1 y bp como los valores de n y h
    n1=n
    F = continued_fraction_periodic(0,1,n)
    L1= [F[0]]+F[1]
    if s<=len(L1):
        L2=list(continued_fraction_convergents(L1[:s]))
    elif s>len(L1):
        return [false,"No se ha podido factorizar el numero con este s, tienes que elegir un s mas pequeño"]

    Pbs=[]
    for i in range(0,len(L2)):
        Pbs.append(fraction(L2[i])[0])
    B=elecbase(Pbs)
    B=orden(B)
    #Elegimos el k y el i y ponemos una condición para terminar el programa
    sol=false
    k1=0
    i1=0
    while sol==false:
        #En cada iteración vamos aumentando los valores de k y de i
        k1=k1+10
        i1=i1+10
        #Nos quedamos con los B-números
        BN=bi(n1,k1,i1,B)
        #Construimos la lista de los alfa vectores asociados a estos B-números
        alfavec=[]
        for i in range(0,len(BN)):
            alfavec.append(vec_alfa(BN[i],B,n1))
        #Hacemos un algoritmo análogo al de la función soleq
        i_0=1 
        i_1=0
        for j in range(i_0,len(alfavec)):
            sumajpar=[]
            in_a=[]
            if j==1:
                #Comprobamos si hay alfavectores pares
                for i in range(0,len(alfavec)):
                    if parp(alfavec[i])==true:
                        sumajpar.append(alfavec[i])
                        in_a.append(i)
                #Comprobamos si los alfavectores pares dan solución 
                for l in range(0,len(in_a)):
                    eles_a=in_a
                    #Calculamos t
                    t=1
                    t=(t*BN[eles_a[l]])%n
                    p=[]
                    e=[]
                    for i in range (0,len(sumajpar)):
                        if sumajpar[l][i]!=0:
                            p.append(B[i])
                            e.append(sumajpar[l][i]/2)
                    #Calculamos s
                    s=1
                    for i in range(0,len(p)):
                        s=(s*pow(p[i],e[i],n))%n
        #Comprobamos que sea una solución no trivial
                    if gcd(s+t,n)!=1:
                        return[true,(t,s)]
            #Comprobamos si hay sumas pares de alfavectores
            if sumajpar==[]:
                in_a=0
                while sumajpar==[]:
                    i_1=0
                    j=j+1
                    if j>=len(alfavec) or j==15:
                        break
                    #Condición para no hacer un bucle infinito
                    elif k==100:
                        return [false]
                    sumaj=suma(alfavec,j)
                    for i in range(i_1,len(sumaj)):
                        if parp(sumaj[i])==true:
                            sumajpar=sumaj[i]
                            in_a=i
                            i_0=j
                            i_1=i   
                        #Vemos que combinación da lugar al vector par
                            eles_a =aux(j,len(BN))
                        #calculamos t
                            t=1
                            for i in range(0,len(eles_a[in_a])):
                                t=(t*BN[eles_a[in_a][i]])%n
                            p=[]
                            e=[]
                            for i in range (0,len(sumajpar)):
                                if sumajpar[i]!=0:
                                    p.append(B[i])
                                    e.append(sumajpar[i]/2)
                            #Calculamos s
                            s=1
                            for i in range(0,len(p)):
                                s=(s*pow(int(p[i]),int(e[i]),int(n)))%n
        #Comprobamos que sea una solución no trivial
                            if gcd(s+t,n)!=1 and gcd(s-t,n)!=1:
                                return[true,(t,s)]
    return [false]

In [53]:
#Vemos que resuelve la ecuación asociada al número que elegimos para hacer el algoritmo paso a paso
sol3=soleqfc(759080391,31)
print sol3
#Resuelve la ecuación
print (sol3[1][0]**2)%759080391-(sol3[1][1]**2)%759080391==0
#¿Es trivial la solución?
print gcd(sol3[1][0]-sol3[1][1],759080391)!=1 and gcd(sol3[1][0]+sol3[1][1],759080391)!=1
#No es trivial ya que ambos gcd son distintos de 1

[True, (105336, 105336)]
True
True


In [54]:
#Probamos con otro número
sol4=soleqfc(170168149,30)
print sol4
#Resuelve la ecuación
print (sol4[1][0]**2)%170168149-(sol4[1][1]**2)%170168149==0
#¿Es trivial la solución?
print gcd(sol4[1][0]-sol4[1][1],170168149)!=1 and gcd(sol4[1][0]+sol4[1][1],170168149)!=1
#No es trivial ya que ambos gcd son distintos de 1

[True, (122304894, 98160982)]
True
True


### Ejercicio 7: Función para factorizar

In [55]:
def facfc(n):
    n1=n
    #Damos un valor de s y un valor máximo de s por defecto, se podrá modificar según el problema al que nos enfrentemos
    s=6
    #Comprobamos si conseguimos factorizar el número para el s dado
    sol=soleqfc(n1,s)
    print sol
    if sol[0]==true:
        print"1"
        q=sol[1][0]
        t=sol[1][1]
    else:
        print "5"
        while sol[0]==false:
            print"2"
        #Vamos ejecutando el método para cada valor de s hasta conseguir solución
            sol=soleqfc(n1,s)
            if sol[0]==true:
                print "3"
                q=sol[1][0]
                t=sol[1][1]
            #Aumentamos el número s
            s=s+3
            #Condición sobre un s máximo para no hacer un bucle infinito
            if s>45:
                return "No hemos podido factorizar el numero"
    print "4"
    #Devolvemos la factorización
    return (gcd(q+t,n),n/gcd(q+t,n))

In [56]:
#Probamos a factorizar el número que hemos usado paso a paso
f=facfc(759080391)
print f
print f[0]*f[1]==759080391

KeyboardInterrupt: 

In [57]:
#Probamos a factorizar otro número
f=facfc(170168149)
print f
#Vemos que la factorización que ha salido es buena
print 170168149==f[0]*f[1]

KeyboardInterrupt: 

In [59]:
facfc(20224)

[True, (2048, 2048)]
1
4


(256, 79)

In [57]:
factorint(20224)

{2: 8, 79: 1}

In [102]:
256*79

20224